import = ["~/.config/alacritty/tokyonight_night.toml"]
live_config_reload = true

[shell]
program = "/usr/local/bin/fish"

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.glyph_offset]
x = 0
y = 0

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"

[window.padding]
x = 10 
y = 10

[keyboard]
bindings=[
{key = "=", mods = "Control", action = "ReceiveChar" },
{key = "_", mods = "Control", action = "ReceiveChar" },
{key = "-", mods = "Control", action = "ReceiveChar" },
{ key = "Tab", mods = "Control", chars = "\u001b[27;5;9~" },
{ key = "Tab", mods = "Control|Shift", chars = "\u001b[27;6;9~" },
{ key = "o", mods = "Control|Shift", chars = "\u001b[27;6;111~" },
]
